### ISSUE TITLE
[Suggestion] add more style, and add image in the mod description by use `github` image link nxt time

### ISSUE THREAD

**Issue by CoolLKKPS** [Sniper1-1/Snipers_Moons#1]
i more prefer the image that linked to the github, not only `security` reason, but also i only use github, im not using discord even i have discord account

> my region banned discord already
> and u already upload the image in the github btw [For example Phuket](https://camo.githubusercontent.com/ebffb233cf8be56e029bbc6f38e47bbcb0050644208d437e8c6e91182843e08f/68747470733a2f2f696d6775722e636f6d2f4546477a6145612e706e67)

ok so far, if just see the mod description, that really cannot convince me to download this moonpack, image are still not enough, i only a bit interest is [Phuket](https://camo.githubusercontent.com/ebffb233cf8be56e029bbc6f38e47bbcb0050644208d437e8c6e91182843e08f/68747470733a2f2f696d6775722e636f6d2f4546477a6145612e706e67), u need to add more style and screenshot tbh

**Comment by CoolLKKPS** [comment]
@Sniper1-1 not a critic, but bc u have been holding on for 6 months, that's why i have this sug, consider add more images

**Comment by Sniper1-1** [comment]
Yeah, descriptions and images could be improved. I am just lazy. If there is a specific one like [Phuket](https://thunderstore.io/c/lethal-company/p/Sniper1_1/69_Phuket/) that potentially seems interesting they all have standalone downloads now, so it should be easier to try specific ones out.

**Comment by CoolLKKPS** [comment]
nice! thx for the reply!
